### ISSUE TITLE
Is it possible to make Random Ferns like classification architecture with UNN ?

### ISSUE THREAD

**Issue by Smithangshu** [photopea/UNN.js#3]
Hi,

I am looking for kind of network architecture which can be trained fast in browser to match image patch of size(32x32px/16x16px) just like Random Ferns is it possible with UNN.js?

**Comment by photopea** [comment]
This library uses the back-propagation algorithm for learning. I think Random Ferns is a completely different algorithm.

Also, this library is for programmers, there is no UI, etc.

**Comment by Smithangshu** [comment]
Basically Random Ferns is the classification algorithm. One can use it for Mnist recognition. So I was thinking it could be possible.

**Comment by photopea** [comment]
Sorry, this library contains only the back-propragation algorithm for training regular neural networks.
