### ISSUE TITLE
Doesnt seem to parse from convnet

### ISSUE THREAD

**Issue by TrevorBlythe** [photopea/UNN.js#6]
I am using

var net = UNN.util.fromCNJS(JSON.parse(mod));
alert(net);

to make a network from a cnjs string;
the mod is a string of the JSON but the code doesn't run after that.
net doesn't alert. Some more useful info might be that the model is
pretty big. Another useful thing to know is that it works when I use convnetjs.

**Comment by photopea** [comment]
Hi, could you share your Convnet network (a JSON file) with us?
